textbox_style = (
    "QLineEdit"
    "{"
    "margin-top : 10px;"
    "margin-bottom : 0px;"
    "margin-left : 100px;"
    "margin-right : 100px;"
    "padding: 10px;"
    "border-radius : 10px;"
    "border-style : solid;"
    "border-width : 0.5px;"
    "border-color : black;"
    "}"
)

primary_cta_style = (
    "QPushButton"
    "{"
    "background-color : #3477eb;"
    "color : white;"
    "width: 70px;"
    "font-weight : bold;"
    "margin-top : 10px;"
    "margin-bottom : 0px;"
    "margin-left : 100px;"
    "margin-right : 100px;"
    "padding: 10px;"
    "border-radius : 5px;"
    "}"
)

create_meeting_cta_style = (
    "QPushButton"
    "{"
    "background-color : #3477eb;"
    "color : white;"
    "font-weight : bold;"
    "padding: 10px;"
    "border-radius : 5px;"
    "}"
)
join_meeting_cta_style = (
    "QPushButton"
    "{"
    "background-color : white;"
    "color : #3477eb;"
    "font-weight : bold;"
    "}"
    "QPushButton::hover"
    "{"
    "background-color : white;"
    "color : #3477eb;"
    "font-weight : bold;"
    "border-radius : 5px;"
    "border-style : solid;"
    "border-width : 0.5px;"
    "border-color : black;"
    "}"
)

secondary_cta_style = (
    "QPushButton"
    "{"
    "background-color : white;"
    "color : #3477eb;"
    "width: 70px;"
    "font-weight : bold;"
    "margin-top : 10px;"
    "margin-bottom : 20px;"
    "margin-left : 100px;"
    "margin-right : 100px;"
    "padding: 10px;"
    "border-radius : 5px;"
    "border-style : none;"
    "border-width : 0.2px;"
    "border-color : black;"
    "}"
    "QPushButton::hover"
    "{"
    "background-color : white;"
    "color : #3477eb;"
    "width: 70px;"
    "font-weight : bold;"
    "margin-top : 10px;"
    "margin-bottom : 20px;"
    "margin-left : 100px;"
    "margin-right : 100px;"
    "padding: 10px;"
    "border-radius : 5px;"
    "border-style : solid;"
    "border-width : 0.5px;"
    "border-color : black;"
    "}"
)

end_meeting_cta_style = (
    "QPushButton"
    "{"
    "background-color : red;"
    "color : white;"
    "width: 70px;"
    "font-weight : bold;"
    "margin-top : 10px;"
    "margin-bottom : 0px;"
    "margin-left : 100px;"
    "margin-right : 100px;"
    "padding: 10px;"
    "border-radius : 5px;"
    "}"
)
