# Form implementation generated from reading ui file 'meeting_design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtGui
from PySide6.QtCore import Qt, QRect, QCoreApplication, QMetaObject
from PySide6.QtWidgets import (
    QWidget,
    QGridLayout,
    QFrame,
    QStackedWidget,
    QHBoxLayout,
    QPushButton,
    QLabel,
    QSizePolicy,
    QSpacerItem
)
from Meeting.chat import ChatScreen
from Meeting.participants import ParticipantScreen
from Meeting.socket_client import SocketClient
from constant import *
from style import end_meeting_cta_style
from ffpyplayer.player import MediaPlayer
from Streaming.receive_stream import ReceiveStream
import time, json

user_stream_player : MediaPlayer = None

class MeetingPage(object):
    def __init__(self, user_details, meeting_id) -> None:
        self.user_details = user_details
        self.user_id = user_details['id']
        self.user_name = user_details['name']
        self.meeting_id = int(meeting_id)
        self.participants_info = dict()
        self.positions = [[0, 1, 1, 1], [1, 0, 1, 1], [1, 1, 1, 1]]
    
        self.socket_client = SocketClient(meeting_id, user_details['id'], user_details['name'])
        self.socket_client.message_received.connect(self.receive_participants)
        self.subscribeToParticpants()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 691)
        sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(
            "background-color: #313a46;\n" 
            "color: rgb(255, 255, 255);"
        )
        self.centralwidget = QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.meeting_container = QWidget(parent=self.centralwidget)
        self.meeting_container.setGeometry(QRect(0, 0, 951, 691))
        self.meeting_container.setStyleSheet("")
        self.meeting_container.setObjectName("meeting_container")
        
        self.video_container = QWidget(parent=self.meeting_container)
        self.video_container.setGeometry(QRect(0, 0, 951, 621))
        self.video_container.setStyleSheet("")
        self.video_container.setObjectName("video_container")
        self.gridLayout = QGridLayout(self.video_container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        
        # Video Display labels
        self.self_video = QLabel(parent=self.video_container)
        self.self_video.setStyleSheet(
            # "border-color: rgb(255, 255, 255);\n" 
            "color: rgb(255, 255, 255);"
        )
        # self.self_video.setFrameShape(QFrame.Shape.Box)
        self.self_video.setScaledContents(True)
        self.self_video.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.self_video.setObjectName("self")
        self.gridLayout.addWidget(self.self_video, 0, 0, 1, 1)
        self.participants_info[str(self.user_id)] = {'label': self.self_video, 'name': self.user_name}
        # self.participant_1 = QLabel(parent=self.video_container)
        # self.participant_1.setStyleSheet(
        #     # "border-color: rgb(255, 255, 255);\n" 
        #     "color: rgb(255, 255, 255);"
        # )
        # # self.participant_1.setFrameShape(QFrame.Shape.Box)
        # self.participant_1.setScaledContents(True)
        # self.participant_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # self.participant_1.setObjectName("participant_1")
        # self.gridLayout.addWidget(self.participant_1, 0, 1, 1, 1)
        
        # self.participant_2 = QLabel(parent=self.video_container)
        # self.participant_2.setStyleSheet(
        #     # "border-color: rgb(255, 255, 255);\n" 
        #     "color: rgb(255, 255, 255);"
        # )
        # # self.participant_2.setFrameShape(QFrame.Shape.Box)
        # self.participant_2.setScaledContents(True)
        # self.participant_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # self.participant_2.setObjectName("participant_2")
        # self.gridLayout.addWidget(self.participant_2, 1, 1, 1, 1)
        
        self.control_container = QWidget(parent=self.meeting_container)
        self.control_container.setGeometry(QRect(0, 620, 961, 71))
        self.control_container.setStyleSheet("")
        self.control_container.setObjectName("control_container")
        self.horizontalLayout = QHBoxLayout(self.control_container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(
            358,
            38,
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.participants_cta = QPushButton(parent=self.control_container)
        self.participants_cta.setStyleSheet(
            "color: rgb(0, 0, 0);\n" "background-color: rgb(255, 255, 255);"
        )
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/icons/Icons/conference-multi-size.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.participants_cta.setIcon(icon)
        self.participants_cta.setObjectName("participants_cta")
        self.horizontalLayout.addWidget(self.participants_cta)
        spacerItem1 = QSpacerItem(
            115,
            38,
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.chat_cta = QPushButton(parent=self.control_container)
        self.chat_cta.setStyleSheet(
            "color: rgb(0, 0, 0);\n" "background-color: rgb(255, 255, 255);"
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/icons/Icons/chat-4-multi-size.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.chat_cta.setIcon(icon1)
        self.chat_cta.setObjectName("chat_cta")
        self.horizontalLayout.addWidget(self.chat_cta)
        spacerItem2 = QSpacerItem(
            148,
            38,
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.end_meeting = QPushButton(parent=self.control_container)
        sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed
        )
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_meeting.sizePolicy().hasHeightForWidth())
        self.end_meeting.setSizePolicy(sizePolicy)
        self.end_meeting.setStyleSheet(
            end_meeting_cta_style
        )
        self.end_meeting.setObjectName("end_meeting")
        self.horizontalLayout.addWidget(self.end_meeting)

        self.stackedWidget = QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QRect(960, 0, 231, 691))
        sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.stackedWidget.sizePolicy().hasHeightForWidth()
        )
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "color: rgb(0, 0, 0);"
        )
        self.stackedWidget.setObjectName("stackedWidget")
        
        self.chat_page = ChatScreen(self.user_details, self.meeting_id, self.socket_client)
        self.chat_page.setObjectName("chat_page")        
        self.stackedWidget.addWidget(self.chat_page)
        
        self.participants_page = ParticipantScreen()
        self.participants_page.setObjectName("participants_page")
        self.stackedWidget.addWidget(self.participants_page)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
          # type: ignore
        self.chat_cta.clicked.connect(self.show_chat)
        self.participants_cta.clicked.connect(self.show_participants)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", f"{self.user_name} - Meeting ({self.meeting_id})"))
        self.self_video.setText(_translate("MainWindow", f"{self.user_name}"))
        # self.participant_1.setText(_translate("MainWindow", "Participant 1"))
        # self.participant_2.setText(_translate("MainWindow", "Participant 2"))
        self.participants_cta.setText(_translate("MainWindow", "Participants"))
        self.chat_cta.setText(_translate("MainWindow", "Chat"))
        self.end_meeting.setText(_translate("MainWindow", "End Meeting"))

    def show_participants(self):
        self.stackedWidget.setCurrentIndex(1)

    def show_chat(self):
        self.stackedWidget.setCurrentIndex(0)

    def subscribeToParticpants(self):
        time.sleep(2)
        if self.socket_client.get_connection_state():
            print("Connected to participants list")
            subscriptionInfo = {"type": f'{PARTICIPANTS_TOPIC}'}
            self.socket_client.send_message(subscriptionInfo)
        else:
            print("Not connected to participants list")
        
    def receive_participants(self, data):
        try:
            if data["type"] == "participantListUpdated":
                self.check_updated_participants(data["participantList"])
                pass
        except Exception as e:
            print(e)

    def check_updated_participants(self, participant_list):
        
            print("Checking updated participants", participant_list)
            print("Participant info", self.participants_info)
            try:
                # Add new participants
                for data in participant_list:
                    participant = json.loads(data)
                    id = participant["id"]
                    name = participant["name"]
                    if not self.participants_info.keys().__contains__(id):
                        print("New participant found", id, name)
                        self.participants_info[id] = {}
                        self.participants_info[id]["name"] = name
                        print("pos", len(self.participants_info)-2)
                        self.addLabel(id, len(self.participants_info)-2)
                        self.display_stream(id)
            except Exception as e:
                print("Exception occured while adding participants :", e)

            # Remove participants
            try:
                print('here1')
                existing_ids = self.getParticipantIds(participant_list)
                user_to_remove = []
                print('existing_ids', existing_ids)
                print('self.participants_info.keys()', self.participants_info.keys())
                for id in self.participants_info.keys():
                    print('id', id)
                    if not existing_ids.__contains__(id):
                        print("Participant left", id)
                        self.participants_info[id]["stream"].stop()
                        self.participants_info[id]["label"].hide()
                        user_to_remove.append(id)
                print('here2')

                for id in user_to_remove:
                    self.participants_info.pop(id)

            except Exception as e:
                print("Exception occured while removing participants :", e)

    
    def getParticipantIds(self, participantList):
        participantIds = []
        for data in participantList:
            participant = json.loads(data)
            participantIds.append(participant["id"])
        return participantIds

    def display_stream(self, user_id):
        try:
            url = f'{RTMP_URL}/{self.meeting_id}_{user_id}'
            self.participants_info[user_id]["stream"] = ReceiveStream(url, user_id)
            self.participants_info[user_id]["stream"].participant_frame_changed.connect(self.on_frame_changed)
            self.participants_info[user_id]["stream"].start()

        except Exception as e:
            print("Exception occured while receiving stream :", e)

    def on_frame_changed(self, pixmap, id):
        # print("pixmap",pixmap)
        # print("id",id)
        # # Change label for each participant
        self.participants_info[id]["label"].setPixmap(pixmap)
        

    def addLabel(self, id, pos):
        self.participants_info[id]["label"] = QLabel(parent=self.video_container)
        self.participants_info[id]["label"].setStyleSheet(
            "color: rgb(255, 255, 255);"
        )
        self.participants_info[id]["label"].setScaledContents(True)
        self.participants_info[id]["label"].setAlignment(Qt.AlignmentFlag.AlignCenter)
        video_positioon = self.positions[pos]
        self.gridLayout.addWidget(self.participants_info[id]["label"], video_positioon[0], video_positioon[1], video_positioon[2], video_positioon[3])

        